language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check -i

after_success:
  - ./gradlew jacocoTestReport codecov
